// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobQBhviXgIgzpjH6fAj3TAwle65bjpAk',
    appId: '1:517844883926:web:c6f8e15c603ee26613ec77',
    messagingSenderId: '517844883926',
    projectId: 'volunterra-d5ac0',
    authDomain: 'volunterra-d5ac0.firebaseapp.com',
    storageBucket: 'volunterra-d5ac0.appspot.com',
    measurementId: 'G-YB590CFCF7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnbLrEPXRfraSoTJsqdqoGBcIdiVZoQE8',
    appId: '1:517844883926:ios:79c433e38d8553f913ec77',
    messagingSenderId: '517844883926',
    projectId: 'volunterra-d5ac0',
    storageBucket: 'volunterra-d5ac0.appspot.com',
    iosBundleId: 'com.example.volunterra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnbLrEPXRfraSoTJsqdqoGBcIdiVZoQE8',
    appId: '1:517844883926:ios:79c433e38d8553f913ec77',
    messagingSenderId: '517844883926',
    projectId: 'volunterra-d5ac0',
    storageBucket: 'volunterra-d5ac0.appspot.com',
    iosBundleId: 'com.example.volunterra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDobQBhviXgIgzpjH6fAj3TAwle65bjpAk',
    appId: '1:517844883926:web:2918033d4b77125c13ec77',
    messagingSenderId: '517844883926',
    projectId: 'volunterra-d5ac0',
    authDomain: 'volunterra-d5ac0.firebaseapp.com',
    storageBucket: 'volunterra-d5ac0.appspot.com',
    measurementId: 'G-0WPFBDZ9CL',
  );
}
